### ISSUE TITLE
Geometrical Source related issues

### ISSUE THREAD

**Issue by xianbo** [oasys-kit/shadow4#15]
1. Angular distribution limits not implemented yet
2. When "Depth" set to "Uniform" or "Gaussian", it runs ok. However, when connect to histogram, y distribution has no change. Also, depth has no unit indicated. 
3. Angular distribution "Flat", "Uniform", "cone", "Collimated" will generate error below

AttributeError                                Traceback (most recent call last):
  File "C:\Users\xianb\miniconda3\lib\site-packages\orangecontrib\shadow4\widgets\sources\ow_geometrical.py", line 716, in run_shadow4
    script = light_source.to_python_code()
  File "C:\Users\xianb\miniconda3\lib\site-packages\shadow4\sources\source_geometrical\source_geometrical.py", line 562, in to_python_code
    (self.__sigmax, self.__sigdiz)
AttributeError: 'SourceGeometrical' object has no attribute '_SourceGeometrical__sigdiz'

**Comment by srio** [comment]
1) Right. Not implemented. I have doubts if we want to implement it or not. Do you use it? 
I think not. It requires adding a rejecting scheme of rays, that slows down. 

The rejecting scheme was also available in shadow3 as "source optimization". Again this is not yet implemented. And I wonder how much this is used. 

My suggestion would be: 
- remove this option of divergence Gaussian limits in geometrical source. 
- implement a scheme of "reject rays" common for all sources giving an acceptance divergence or an acceptance slit. 

Comments welcomed!

2) Deph was not implemented. I just added it.   

3) I cannot reproduce this error. To be verified again.

**Comment by srio** [comment]
I removed the limits in the Gaussian distribution. Not available in S4.
